model:
  input_dim: 512  # Dimension of the concept dataset
  hidden_dim: 2048  # 4x overcomplete
  k: 64  # Top-k sparsity
  tied_weights: true
  normalize_decoder: true
  bias: true
  dtype: float32

data:
  dataset_name: "https://github.com/peterljq/Parsimonious-Concept-Engineering/raw/main/data/concept.tar.gz"
  cache_dir: "./cache"

training:
  num_epochs: 10
  learning_rate: 0.001
  optimizer: "adam"
  weight_decay: 0.0001
  l1_lambda: 0.0001  # L1 sparsity penalty
  grad_clip_norm: 1.0
  batch_size: 256  # Training batch size
  val_batch_size: 512
  train_val_split: 0.9
  scheduler: null
  scheduler_params: {}
  eval_every: 1000
  save_every: 5000
  log_every: 100
  max_steps: null
  early_stopping_patience: null
  use_wandb: true
  wandb_project: "absolute-topk-sae-concept"
  log_dir: "logs"
  checkpoint_dir: "checkpoints"
