data:
  batch_size: 8
  cache_dir: ./cache
  dataset_name: https://github.com/peterljq/Parsimonious-Concept-Engineering/raw/main/data/concept.tar.gz
  dataset_split: train
  layer_name: null
  max_length: 512
  model_name: null
  num_samples: null
  save_activations_path: null
  streaming: false
model:
  bias: true
  dtype: float32
  hidden_dim: 2048
  input_dim: 512
  k: 64
  normalize_decoder: true
  tied_weights: true
training:
  batch_size: 256
  checkpoint_dir: checkpoints
  early_stopping_patience: null
  eval_every: 1000
  grad_clip_norm: 1.0
  l1_lambda: 0.0001
  learning_rate: 0.001
  log_dir: logs
  log_every: 100
  max_steps: null
  num_epochs: 10
  optimizer: adam
  save_every: 5000
  scheduler: null
  scheduler_params: {}
  train_val_split: 0.9
  use_wandb: true
  val_batch_size: 512
  wandb_project: absolute-topk-sae-concept
  weight_decay: 0.0001
