aux_penalty: 0.03125
bandwidth: 0.001
batch_size: 128
config_save_path: ./configs/
dataset: Skylion007/openwebtext
device: cuda
dictionary_factor: 16
input_unit_norm: true
k: 230
l1_coeff: 0
layer: 8
log_path: ./logs/
lr: 0.0003
model_name: EleutherAI/pythia-70m
sae_name: topk
save_steps: 0.004
seed: 42
steps: 10000
torch_dtype: bfloat16
verbose: true
