add_special_token: true
auxk_alpha: 0.03125
batch_size: 16
config_save_path: ./configs/
ctx_len: 1024
dataset: monology/pile-uncopyrighted
decay_start: null
device: cuda
dictionary_factor: 8
k: 50
log_path: ./logs/
lr: 1.0e-05
model_layer: 3
model_name: EleutherAI/pythia-70m
n_ctxs: 1000
normalize_activations: false
remove_bos: false
sae_name: absolutek
save_ratio: 0.1
seed: 42
steps: 20000
threshold_beta: 0.999
threshold_start_step: 1000
torch_dtype: bfloat16
verbose: true
